# Generated by Django 5.1.3 on 2024-11-16 10:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='../media/item-images/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_receipt',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='../media/customer-receipt/'), upload_to=''),
        ),
    ]
