# Generated by Django 5.1 on 2024-11-18 08:17

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_itemimage_image_alter_order_customer_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('cover', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='../media/brand-cover/'), upload_to='')),
            ],
        ),
    ]
